import enum
from collections import OrderedDict


class Site(enum.Enum):
    CHESSCOM = "chesscom"
    LICHESS = "lichess"


class Title(enum.Enum):
    GM = "GM"  # Grandmaster
    IM = "IM"  # International master
    FM = "FM"  # FIDE master
    CM = "CM"  # Candidate master
    NM = "NM"  # National master
    WGM = "WGM"
    WIM = "WIM"
    WFM = "WFM"
    WCM = "WCM"
    WNM = "WNM"


class Language(enum.Enum):
    en_GB = "English"
    af_ZA = "Afrikaans"
    an_ES = "Aragonés"
    ar_SA = "العربية"
    as_IN = "অসমীয়া"
    av_DA = "авар мацӀ"
    az_AZ = "Azərbaycanca"
    be_BY = "Беларуская"
    bg_BG = "български език"
    bn_BD = "বাংলা"
    br_FR = "Brezhoneg"
    bs_BA = "Bosanski"
    ca_ES = "Català, valencià"
    ckb_IR = "کوردی سۆرانی"
    co_FR = "Corsu"
    cs_CZ = "Čeština"
    cv_CU = "чӑваш чӗлхи"
    cy_GB = "Cymraeg"
    da_DK = "Dansk"
    de_DE = "Deutsch"
    el_GR = "Ελληνικά"
    en_US = "English (US)"
    eo_UY = "Esperanto"
    es_ES = "Español"
    et_EE = "Eesti keel"
    eu_ES = "Euskara"
    fa_IR = "فارسی"
    fi_FI = "Suomen kieli"
    fo_FO = "Føroyskt"
    fr_FR = "Français"
    frp_IT = "Arpitan"
    fy_NL = "Frysk"
    ga_IE = "Gaeilge"
    gd_GB = "Gàidhlig"
    gl_ES = "Galego"
    gsw_CH = "Schwizerdütsch"
    gu_IN = "ગુજરાતી"
    he_IL = "עִבְרִית"
    hi_IN = "हिन्दी, हिंदी"
    hr_HR = "Hrvatski"
    hu_HU = "Magyar"
    hy_AM = "Հայերեն"
    ia_IA = "Interlingua"
    id_ID = "Bahasa Indonesia"
    io_EN = "Ido"
    is_IS = "Íslenska"
    it_IT = "Italiano"
    ja_JP = "日本語"
    jbo_EN = "Lojban"
    jv_ID = "Basa Jawa"
    ka_GE = "ქართული"
    kab_DZ = "Taqvaylit"
    kk_KZ = "қазақша"
    kmr_TR = "Kurdî (Kurmancî)"
    kn_IN = "ಕನ್ನಡ"
    ko_KR = "한국어"
    ky_KG = "кыргызча"
    la_LA = "Lingua Latina"
    lb_LU = "Lëtzebuergesch"
    lt_LT = "Lietuvių kalba"
    lv_LV = "Latviešu valoda"
    mg_MG = "Fiteny malagasy"
    mk_MK = "македонски јази"
    ml_IN = "മലയാളം"
    mn_MN = "монгол"
    mr_IN = "मराठी"
    nb_NO = "Norsk bokmål"
    ne_NP = "नेपाली"
    nl_NL = "Nederlands"
    nn_NO = "Norsk nynorsk"
    pi_IN = "पालि"
    pl_PL = "Polski"
    ps_AF = "پښتو"
    pt_PT = "Português"
    pt_BR = "Português (BR)"
    ro_RO = "Română"
    ru_RU = "русский язык"
    ry_UA = "Русинська бисїда"
    sa_IN = "संस्कृत"
    sk_SK = "Slovenčina"
    sl_SI = "Slovenščina"
    sq_AL = "Shqip"
    sr_SP = "Српски језик"
    sv_SE = "Svenska"
    sw_KE = "Kiswahili"
    ta_IN = "தமிழ்"
    tg_TJ = "тоҷикӣ"
    th_TH = "ไทย"
    tk_TM = "Türkmençe"
    tl_PH = "Tagalog"
    tp_TP = "Toki pona"
    tr_TR = "Türkçe"
    uk_UA = "українська"
    ur_PK = "اُردُو"
    uz_UZ = "oʻzbekcha"
    vi_VN = "Tiếng Việt"
    yo_NG = "Yorùbá"
    zh_CN = "中文"
    zh_TW = "繁體中文"
    zu_ZA = "isiZulu"


code_to_lang = OrderedDict(
    [(lang.name.replace("_", "-"), lang.value) for lang in Language]
)

lang_to_code = OrderedDict(
    [(lang.value, lang.name.replace("_", "-")) for lang in Language]
)
